# Generated by Django 4.0 on 2024-05-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('position', models.IntegerField()),
                ('key', models.SlugField()),
                ('icon_image', models.ImageField(upload_to='guideicon/')),
            ],
        ),
        migrations.CreateModel(
            name='GuideMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('position', models.IntegerField()),
                ('slug', models.SlugField()),
                ('guidetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeofguide', to='guide.guidetype')),
            ],
        ),
        migrations.CreateModel(
            name='GenarelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('position', models.IntegerField()),
                ('anchor', models.CharField(max_length=252)),
                ('content', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuofguide', to='guide.guidemenu')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menuchild', to='guide.genarelguide')),
            ],
        ),
    ]
