# Generated by Django 4.0 on 2024-05-23 18:55

import django.contrib.sites.managers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=256)),
                ('button_des', models.TextField()),
                ('apps', models.CharField(choices=[('administration', 'Administration'), ('authentication-and-authorization', 'Authentication and Authorization'), ('content-types', 'Content Types'), ('sessions', 'Sessions'), ('messages', 'Messages'), ('static-files', 'Static Files'), ('django-summernote', 'Django Summernote'), ('debug-toolbar', 'Debug Toolbar'), ('sites', 'Sites'), ('site-maps', 'Site Maps'), ('axes', 'Axes'), ('accounts', 'Accounts'), ('home', 'Home'), ('evaluation', 'Evaluation'), ('crm', 'Crm'), ('doc', 'Doc'), ('captcha', 'Captcha'), ('guide', 'Guide'), ('maintenance_mode', 'Maintenance_Mode'), ('blog', 'Blog'), ('taggit', 'Taggit'), ('taggit_autosuggest', 'Taggit_Autosuggest'), ('import_export', 'Import_Export'), ('django_cron', 'Django_Cron'), ('django-extensions', 'Django Extensions'), ('smart_selects', 'Smart_Selects'), ('django_mkdocs', 'Django_Mkdocs'), ('glossary', 'Glossary'), ('feedback', 'Feedback'), ('navigation', 'Navigation'), ('gf_cookies', 'Gf_Cookies')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExSite',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site', verbose_name='site')),
                ('site_meta', models.CharField(max_length=256)),
                ('site_description', models.TextField(max_length=500)),
                ('site_meta_tag', models.CharField(max_length=255)),
                ('site_favicon', models.ImageField(upload_to='site_image')),
                ('site_logo', models.ImageField(upload_to='site_image')),
                ('slogan', models.CharField(default='', max_length=150)),
                ('og_image', models.ImageField(upload_to='site_image')),
                ('mask_icon', models.FileField(upload_to='site_image', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=120)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('qualified_ans_range', models.IntegerField(default=1)),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
