# Generated by Django 4.0 on 2024-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordion',
            name='apps',
            field=models.CharField(choices=[('administration', 'Administration'), ('authentication-and-authorization', 'Authentication and Authorization'), ('content-types', 'Content Types'), ('sessions', 'Sessions'), ('messages', 'Messages'), ('static-files', 'Static Files'), ('django-summernote', 'Django Summernote'), ('debug-toolbar', 'Debug Toolbar'), ('sites', 'Sites'), ('site-maps', 'Site Maps'), ('axes', 'Axes'), ('accounts', 'Accounts'), ('home', 'Home'), ('evaluation', 'Evaluation'), ('crm', 'Crm'), ('doc', 'Doc'), ('django-recaptcha', 'Django reCAPTCHA'), ('guide', 'Guide'), ('maintenance_mode', 'Maintenance_Mode'), ('blog', 'Blog'), ('taggit', 'Taggit'), ('taggit_autosuggest', 'Taggit_Autosuggest'), ('import_export', 'Import_Export'), ('django_cron', 'Django_Cron'), ('django-extensions', 'Django Extensions'), ('smart_selects', 'Smart_Selects'), ('django_mkdocs', 'Django_Mkdocs'), ('glossary', 'Glossary'), ('feedback', 'Feedback'), ('navigation', 'Navigation'), ('gf_cookies', 'Gf_Cookies')], max_length=50),
        ),
    ]
