# Generated by Django 4.0 on 2024-05-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('evaluation', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersnextactivity',
            name='next_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_activities', to='evaluation.nextactivities'),
        ),
        migrations.AddField(
            model_name='usersnextactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_next_activity', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='experts_in',
            field=models.ForeignKey(blank=True, limit_choices_to={'common_status': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_label', to='evaluation.difinedlabel'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usertype', to='accounts.usertype'),
        ),
    ]
