# Generated by Django 4.0 on 2024-05-23 18:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=256, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('process_time', models.DateTimeField(auto_now=True)),
                ('tried', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerMailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=256, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('process_time', models.DateTimeField(auto_now=True)),
                ('tried', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(max_length=256)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('address_1', models.CharField(blank=True, max_length=256, null=True)),
                ('address_2', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('confirm_code', models.CharField(default='702612964554', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=256, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('process_time', models.DateTimeField(auto_now=True, null=True)),
                ('tried', models.IntegerField(default=0)),
            ],
        ),
    ]
