# Generated by Django 4.0 on 2024-05-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('crm', '0001_initial'),
        ('evaluation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumermailqueue',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.evaluator'),
        ),
        migrations.AddField(
            model_name='blogmailqueue',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
    ]
